export const usageExamples = [
  {
    key: 'thesis',
    title: '教育心理学论文段落',
    docType: 'Academic',
    length: '1200 words',
    description: '研究生论文关于课堂互动的论证段落，包含引用与方法描述。',
    ai: 22,
    mixed: 18,
    human: 60,
    snapshot: '章节摘要 + 标色句子',
    snippet: '本研究通过对 46 份课堂观察记录进行扎根理论编码，进一步提炼出互动质量指标与学生自我效能之间的非线性关系。',
  },
  {
    key: 'marketing',
    title: '品牌营销落地页',
    docType: 'Marketing',
    length: '780 words',
    description: '面向高校的 AI 评分助手推广页，突出效率提升与团队协作。',
    ai: 35,
    mixed: 28,
    human: 37,
    snapshot: 'AI 概率分布 + CTA 建议',
    snippet: '我们为教师提供统一的反馈模板与语气库，让跨课程的评分标准更加一致，同时保留个性化的书写空间。',
  },
  {
    key: 'technical',
    title: '技术设计文档',
    docType: 'Technical',
    length: '6 pages',
    description: '数据清洗流水线的设计提案，包含风险提示与性能指标。',
    ai: 18,
    mixed: 24,
    human: 58,
    snapshot: '风险提示 + 改写建议',
    snippet: '为避免批量检测阻塞，我们将文件分片上传并行处理，并在队列服务中设置退避重试策略以稳定延迟。',
  },
];
